"""add activity, category

Revision ID: 3d8a9488ded5
Revises: 6a1a38d6fe04
Create Date: 2026-04-15 15:21:53.096019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d8a9488ded5'
down_revision: Union[str, Sequence[str], None] = '6a1a38d6fe04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('logged_date', sa.Date(), nullable=False))
    op.alter_column('activities', 'unit_count',
               existing_type=sa.NUMERIC(precision=6, scale=1),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('activities', 'earned_points',
               existing_type=sa.NUMERIC(precision=6, scale=1),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_column('activities', 'updated_at')
    op.alter_column('categories', 'points_per_unit',
               existing_type=sa.NUMERIC(precision=4, scale=1),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'points_per_unit',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=4, scale=1),
               existing_nullable=False)
    op.add_column('activities', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.alter_column('activities', 'earned_points',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=6, scale=1),
               existing_nullable=False)
    op.alter_column('activities', 'unit_count',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=6, scale=1),
               existing_nullable=False)
    op.drop_column('activities', 'logged_date')
    # ### end Alembic commands ###
